### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by whateverqaq** [JPYamamoto/Issuu-PDF-Downloader#4]
Enter the url of the PDF:https://issuu.com/capitalmag/docs/capital_71
Traceback (most recent call last):
  File "framework.py", line 53, in <module>
    main()
  File "framework.py", line 18, in main
    url = input("Enter the url of the PDF:")
  File "<string>", line 1
    https://issuu.com/capitalmag/docs/capital_71
         ^
SyntaxError: invalid syntax

Now this is the trouble, could you help me?
Thank you very much.

**Comment by jpyamamoto** [comment]
I could not replicate the issue. Did you make any modification to the code? What is your python version?

**Comment by whateverqaq** [comment]
> I could not replicate the issue. Did you make any modification to the code? What is your python version?

Thanks for your reply. I didn't. Python 2.7.10

**Comment by jpyamamoto** [comment]
That might be the reason why it is not working. You should run it with python 3.x.x.

**Comment by whateverqaq** [comment]
I updated it to python 3.8.3, and changed it as the default python
successfully. But it doesn't work.

Traceback (most recent call last):

  File "framework.py", line 53, in <module>

    main()

  File "framework.py", line 15, in main

    import core.downloader as program

  File
"/Users/apple/Downloads/Issuu-PDF-Downloader-master/core/downloader.py",
line 1, in <module>

    import core.resizer as scale

  File
"/Users/apple/Downloads/Issuu-PDF-Downloader-master/core/resizer.py", line
1, in <module>

    from PIL import Image

ModuleNotFoundError: No module named 'PIL'

Sorry for trouble you, what's the problem?

Juan Pablo Yamamoto <notifications@github.com> 于2020年6月30日周二 上午1:23写道：

**Comment by jpyamamoto** [comment]
You should have the following python packages installed:
- Pillow
- requests
- fpdf

**Comment by whateverqaq** [comment]
I installed them, and I could get to the step "enter the url", but when I
did it, like that. It is very long, what's the problem?

Enter the url of the PDF:
https://issuu.com/casaricordi/docs/2344-sori-partitur

Traceback (most recent call last):

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py",
line 1350, in do_open

    h.request(req.get_method(), req.selector, req.data, headers,

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py",
line 1240, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py",
line 1286, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py",
line 1235, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py",
line 1006, in _send_output

    self.send(msg)

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py",
line 946, in send

    self.connect()

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py",
line 1409, in connect

    self.sock = self._context.wrap_socket(self.sock,

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py",
line 500, in wrap_socket

    return self.sslsocket_class._create(

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py",
line 1040, in _create

    self.do_handshake()

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py",
line 1309, in do_handshake

    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed: unable to get local issuer certificate (_ssl.c:1108)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "framework.py", line 53, in <module>

    main()

  File "framework.py", line 35, in main

    url_open1 = str(urllib.request.urlopen(url).read().decode("utf-8"))

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py",
line 222, in urlopen

    return opener.open(url, data, timeout)

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py",
line 525, in open

    response = self._open(req, data)

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py",
line 542, in _open

    result = self._call_chain(self.handle_open, protocol, protocol +

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py",
line 502, in _call_chain

    result = func(*args)

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py",
line 1393, in https_open

    return self.do_open(http.client.HTTPSConnection, req,

  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py",
line 1353, in do_open

    raise URLError(err)

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: unable to get local issuer certificate
(_ssl.c:1108)>



Juan Pablo Yamamoto <notifications@github.com> 于2020年7月6日周一 上午7:10写道：

**Comment by jpyamamoto** [comment]
It seems like it has to do with the SSL certificate (maybe an issue with your ISP?) but I couldn't replicate it. There are a few proposed solutions online, I suggest you check out the requests' docs, there's a section on [SSL Cert Verification](https://requests.readthedocs.io/en/master/user/advanced/#ssl-cert-verification).  
Feel free to send a pull request.

**Comment by whateverqaq** [comment]
The delivery falied. Let me send it again

 output.pdf
<https://drive.google.com/file/d/1F_vS_iBdzFPrI_a9Le26EhhdlDmKk8DQ/view?usp=drive_web>


I opened the link but unfortunately I didn't understand, I searched by
google and finally I solved the problem by "/Applications/Python\
3.8/Install\ Certificates.command"
I tried it, the 1st time failed on page 31 but next time it completely
worked. One thing I want to confirm is that the pdf which is downloaded is
the same quality as the original? Like this
https://www.youtube.com/watch?v=2Zdy3sQVt7U but his tool is only valid on
Windows, I use a macbook.
This is the pdf I just downloaded, the size should be changed of course,
but when I expanded it it seemed to be compressed like downloading by some
websites. So how would it be?

Juan Pablo Yamamoto <notifications@github.com> 于2020年7月8日周三 上午12:11写道：
